version: '3'
services:

  anaconda3:
    privileged: true
    image: tossy0423/anaconda:cuda11-cudnn8

    ## GPU Settings
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    
    ## Setting of Volumes
    volumes:
      - ${PWD}:/home/workspace:rw
    
    stdin_open: true

