version: '3'
services:

  ## Service name
  anaconda3:

    ## Set shared memory
    build: 
      context: .
      shm_size: '2gb'

    ## Set container name
    container_name: anaconda-gpu

    ## Allow device control from Docker container.
    privileged: true

    ## Launch shell
    stdin_open: true
    
    ## Set port
    ## Jupyter notebook is necessary to operate from a browser.
    ports:
      - 8888:8888

    ## When OS rebooted, this container auto start.
    restart: always

    ## Set docker image
    image: tossy0423/anaconda:cuda11-cudnn8


    ## Set environment values
    environment:
      ## For X11 server
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      ## For Nvidia docker environment values
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    

    ## GPU Settings
    runtime: nvidia
      
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    

    ## Setting of Volumes and working directory
    volumes:
      - ./:/root/workspace:rw
      - /dev:/dev:rw
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    working_dir: /root/workspace




