name: Anaconda3 x86

on:
  push:
    branches: 
      - main

jobs:
  build-from-dockerfile:
    runs-on: ubuntu-18.04
    env:
      IMAGE_NAME: build-dockerimage

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true

      - name: Build
        run: |
          docker build ./Anaconda3/x86
